global:
  jump_server:
    non_prod:
      host: "HBDUAS10V.CUSCALAD.COM"
    prod:
      host: "PROD.CUSCALAD.COM"
  working_dir: "/app/automation"
  email_server: "HBUAS10V.CUSCALAD.COM"
  to_email: "v-akarthik@cuscal.com.au"
