atm-onboarding-for-dcc-config:
  required_inputs:
    - automation_task
    - environment
    - environment_type
    - target_host
    - db_host
    - db_port
    - db_name
  default_values:
    environment: "dev"
    environment_type: "onpremise"
  validation:
    db_port:
      type: "integer"
      range: [1024, 65535]
    environment:
      allowed_values: ["dev", "test", "qa", "preprod", "prod"]
    environment_type:
      allowed_values: ["onpremise", "cloud"]
