name: Task Flow | TSR Auto-Approval

on:
  workflow_dispatch:
  inputs:
    application:
      description: "Select the application"
      required: true
      type: choice
      options: ['generic']

    automation_task:
      description: "Select the automation task"
      required: true
      type: choice
      options: ['tsr-auto-approval']

    action:
      description: "Select the action"
      required: true
      type: choice
      options: ['run', 'delete']

    environment:
      description: "Target environment"
      required: true
      type: choice
      options: ['UAT', 'PROD']

    data_centers:
      description: "Select the data centers (for on-premise environments)"
      required: false
      type: choice
      options: ['ultimo', 'homebush']

    parameters:
      description: "Additional parameters in JSON format"
      required: false
      default: "{}"

schedule:
  - cron: ""
  - cron: ""
  - cron: "0 6 * * *"
  - cron: "0 7 * * *"

jobs: