name: Automation Pipeline -  [postilion-office-portal/portal-restart]

on:
  workflow_dispatch:
    inputs:
      application:
        description: "Select the application"
        required: true
        type: choice
        options: 'postilion-office-portal'

      automation_task:
        description: "Select the automation task"
        required: true
        type: choice
        options: 'portal-restart'

      action:
        description: "Select the action"
        required: true
        type: choice
        options: ['restart', 'stop', 'start']

      environment:
        description: "Target environment"
        required: true
        type: choice
        options: ['QA']

      data_centers:
        description: "Select the data centers (for on-premise environments)"
        required: false
        type: choice
        options: ['ultimo', 'homebush']

      parameters:
        description: "Additional parameters in JSON format"
        required: false
        default: "{{}}"

jobs:
  execute:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read and Validate Input Parameters
        run: |
          echo "Application: ${{{{ inputs.application }}}}"
          echo "Task: ${{{{ inputs.automation_task }}}}"
          echo "Action: ${{{{ inputs.action }}}}"
          echo "Environment: ${{{{ inputs.environment }}}}"
          echo "Data Centers: ${{{{ inputs.data_centers }}}}"
          echo "Parameters: ${{{{ inputs.parameters }}}}"

      - name: Execute Automation Task
        run: |
          python automation_runner.py \\
            --application "${{{{ inputs.application }}}}" \\
            --task_type "${{{{ inputs.automation_task }}}}" \\
            --action "${{{{ inputs.action }}}}" \\
            --environment "${{{{ inputs.environment }}}}" \\
            --data_centers "${{{{ inputs.data_centers }}}}" \\
            --params '${{{{ inputs.parameters }}}}'
