name: Automation Pipeline | ATM Onboarding

on:
  workflow_dispatch:
  inputs:
    application:
      description: "Select the application"
      required: true
      type: choice
      options: ['postilion-device-driver']

    automation_task:
      description: "Select the automation task"
      required: true
      type: choice
      options: ['atm-onboarding-for-dcc']

    action:
      description: "Select the action"
      required: true
      type: choice
      options: ['install', 'run', 'delete']

    environment:
      description: "Target environment"
      required: true
      type: choice
      options: ['DEV', 'QA', 'PROD']

    data_centers:
      description: "Select the data centers (for on-premise environments)"
      required: false
      type: choice
      options: ['ultimo']

    parameters:
      description: "Additional parameters in JSON format"
      required: false
      default: "{}"

schedule:
  - cron: "15 1 * * *"
  - cron: "30 2 * * *"
  - cron: ""
  - cron: "45 3 * * *"

jobs: