name: InstallMaster

on:
  workflow_dispatch:
    inputs:
      install_type:
        description: 'Type of installation'
        required: true
        type: choice
        options:
          - install-post-office-file-cleanup-utility
          - install-tsr-auto-approval-scripts
          - install-atm-onboarding-scripts
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - DEV
          - TEST
          - QA
  repository_dispatch:
    types: [trigger-install]
    inputs:
      install_type:
        description: 'Type of installation'
        required: true
      environment:
        description: 'Target environment'
        required: true

jobs:
  determine-job:
    runs-on: ubuntu-latest
    outputs:
      selected_job: ${{ steps.set-job.outputs.selected_job }}
    steps:
      - name: Determine job based on inputs
        id: set-job
        run: |
          INSTALL_TYPE=${{ github.event.inputs.install_type }}
          case "$INSTALL_TYPE" in
            install-post-office-file-cleanup-utility)
              echo "selected_job=install-post-office-file-cleanup-utility" >> $GITHUB_OUTPUT;;
            install-tsr-auto-approval-scripts)
              echo "selected_job=install-tsr-auto-approval-scripts" >> $GITHUB_OUTPUT;;
            install-atm-onboarding-scripts)
              echo "selected_job=install-atm-onboarding-scripts" >> $GITHUB_OUTPUT;;
          esac

  install-post-office-file-cleanup-utility:
    needs: determine-job
    if: needs.determine-job.outputs.selected_job == 'install-post-office-file-cleanup-utility'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load configuration
        run: |
          CONFIG_FILE=inventory/config.yaml
          ENVIRONMENT=${{ github.event.inputs.environment }}
          CONFIG=$(yq eval ".install-scripts.install-post-office-file-cleanup-utility.$ENVIRONMENT" "$CONFIG_FILE")
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Run installation script
        run: |
          INSTALL_SCRIPT="install-scripts/install-post-office-file-cleanup-utility/install.sh"
          chmod +x "$INSTALL_SCRIPT"
          "$INSTALL_SCRIPT" $CONFIG

  install-tsr-auto-approval-scripts:
    needs: determine-job
    if: needs.determine-job.outputs.selected_job == 'install-tsr-auto-approval-scripts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load configuration
        run: |
          CONFIG_FILE=inventory/config.yaml
          ENVIRONMENT=${{ github.event.inputs.environment }}
          CONFIG=$(yq eval ".install-scripts.install-tsr-auto-approval-scripts.$ENVIRONMENT" "$CONFIG_FILE")
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Run installation script
        run: |
          INSTALL_SCRIPT="install-scripts/install-tsr-auto-approval-scripts/install.sh"
          chmod +x "$INSTALL_SCRIPT"
          "$INSTALL_SCRIPT" $CONFIG

  install-atm-onboarding-scripts:
    needs: determine-job
    if: needs.determine-job.outputs.selected_job == 'install-atm-onboarding-scripts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load configuration
        run: |
          CONFIG_FILE=inventory/config.yaml
          ENVIRONMENT=${{ github.event.inputs.environment }}
          CONFIG=$(yq eval ".install-scripts.install-atm-onboarding-scripts.$ENVIRONMENT" "$CONFIG_FILE")
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Run installation script
        run: |
          INSTALL_SCRIPT="install-scripts/install-atm-onboarding-scripts/install.sh"
          chmod +x "$INSTALL_SCRIPT"
          "$INSTALL_SCRIPT" $CONFIG