name: Final Scheduler

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Name'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - TEST
          - QA

  schedule:
    - cron: '*/5 10-12 * * 1-5'  # Runs every 5 minutes between 9 PM - 6 AM AEDT (Previous day UTC)
    - cron: '*/5 13-18 * * 1-5'  # Runs every 5 minutes between 12 AM - 6 AM AEDT (Same day UTC)


jobs:
  atm-onboarding-for-dcc-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Copy scripts to Jump server   
        run: | 
          
          echo "Environment: ${{ github.event.schedule }}"
          